- name: Installaing Redis Yum Repository
  ansible.builtin.yum:
    name: https://rpms.remirepo.net/enterprise/remi-release-8.rpm -y
    state: installed

- name: Enabling Redis Package Streams
  ansible.builtin.shell: https://rpms.remirepo.net/enterprise/remi-release-8.rpm -y

- name: Install redis server
  ansible.builtin.yum:
    name: redis
    state: installed

- name: Update Redis Listen Address
  ansible.builtin.replace:
    path: /etc/redis.conf
    regexp: '127.0.0.1'
    replace: '0.0.0.0'

- name: Start redis
  ansible.builtin.systemd:
    state: restarted
    enabled: yes