- name: Installing Redis Yum Repository
  ansible.builtin.yum:
    name: https://rpms.remirepo.net/enterprise/remi-release-8.rpm
    state: installed
    disable_gpg_check: true

- name: Enabling Redis Package Streams
  ansible.builtin.shell: yum module enable redis:remi-6.2 -y

  
- name: Install redis server
  ansible.builtin.yum:
    name: redis
    state: installed

- name: Update Redis Listen Address
  ansible.builtin.replace:
    path: /etc/redis.conf
    regexp: '127.0.0.1'
    replace: '0.0.0.0'

- name: Start redis
  ansible.builtin.systemd:
    state: restarted
    enabled: yes