- name: Install Nginx
  ansible.builtin.yum:
    name: nginx
    state: installed
- name: Remove Old HTTP Documents
  ansible.builtin.file:
    path: /usr/share/nginx/html
    state: absent

- name: Creating HTTP Directory
  ansible.builtin.file:
    path: /usr/share/nginx/html
    state: directory