- name: Install Nginx
  ansible.builtin.yum:
    name: nginx
    state: installed

- name: Install Unzip
  ansible.builtin.yum:
    name: unzip
    state: installed

- name: Remove Old HTTP Documents
  ansible.builtin.file:
    path: /usr/share/nginx/html
    state: absent

- name: Creating HTTP Directory
  ansible.builtin.file:
    path: /usr/share/nginx/html
    state: directory

- name: Download frontend App content
  ansible.builtin.unarchive:
    src: https://roboshop-artifacts.s3.amazonaws.com/frontend.zip
    dest: /usr/share/nginx/html
    remote_src: yes

- name: Copy Roboshop config file to nginx
  ansible.builtin.template:
    src: roboshop.conf
    dest: /etc/nginx/default.d/roboshop.conf

- name: Start Nginx Service
  ansible.builtin.systemd:
    state: restarted
    name: nginx
    enabled: yes