- name: Creating app Directory
  ansible.builtin.file:
    path: /opt/prometheus
    state: directory

- name: Download Prometheus archive
  ansible.builtin.get_url:
    url: https://github.com/prometheus/prometheus/releases/download/v2.46.0/prometheus-2.46.0.linux-amd64.tar.gz
    dest: /tmp/prometheus-2.46.0.linux-amd64.tar.gz

- name: Unarchive Prometheus
  ansible.builtin.unarchive:
    src: /tmp/prometheus-2.46.0.linux-amd64.tar.gz
    dest: /opt/prometheus  # Destination directory path
    remote_src: yes
    extra_opts: "--strip-components=1"  # Use this option to remove the parent directory (prometheus-2.46.0.linux-amd64) during extraction

- name: Copy SystemD file
  ansible.builtin.template:
    src: "prometheus.service"
    dest: /etc/systemd/system/prometheus.service


- name: Enable Prometheus service on boot
  ansible.builtin.systemd:
      name: prometheus
      state: started
      enabled: yes
      daemon_reload: yes





















#- name: Setup Server
#  ansible.builtin.include_tasks: "server.yml"
#  when: prometheus == "server"
#
#- name: Setup Exporter
#  ansible.builtin.include_tasks: "exporter.yml"
#  when: prometheus == "exporter"