- name: Creating app Directory
  ansible.builtin.file:
    path: /opt/prometheus
    state: directory

- name: Downloading Prometheus
  ansible.builtin.unarchive:
    src: https://github.com/prometheus/prometheus/releases/download/v2.46.0/prometheus-2.46.0.linux-amd64.tar.gz
    dest: /opt/prometheus
    remote_src: yes

- name: Copy SystemD file
  ansible.builtin.template:
    src: "prometheus.service"
    dest: /etc/systemd/system/prometheus.service

- name: Enable Prometheus service on boot
  ansible.builtin.systemd:
      name: prometheus
      state: started
      enabled: yes






















#- name: Setup Server
#  ansible.builtin.include_tasks: "server.yml"
#  when: prometheus == "server"
#
#- name: Setup Exporter
#  ansible.builtin.include_tasks: "exporter.yml"
#  when: prometheus == "exporter"