- name: Creating app Directory
  ansible.builtin.file:
    path: /opt/prometheus
    state: directory

- name: Downloading Prometheus
  ansible.builtin.unarchive:
    src: https://github.com/prometheus/prometheus/releases/download/v2.46.0/prometheus-2.46.0.linux-amd64.tar.gz
    dest: /opt/prometheus-2.46.0.linux-amd64.tar.gz
    remote_src: yes
  register: prometheus_archive

- name: Extract Prometheus
  ansible.builtin.unarchive:
    src: "{{ prometheus_archive.dest }}"
    dest: /opt/
    remote_src: no
  when: prometheus_archive|changed

- name: Rename Prometheus directory
  ansible.builtin.file:
    src: "/opt/prometheus-2.46.0.linux-amd64"
    dest: "/opt/prometheus"
    state: link

- name: Copy SystemD file
  ansible.builtin.template:
    src: "prometheus.service"
    dest: /etc/systemd/system/prometheus.service
#
##- name: Ensure Prometheus binary has execute permission
##  ansible.builtin.shell: sudo chown -R prometheus:prometheus /opt/prometheus
#
- name: Enable Prometheus service on boot
  ansible.builtin.systemd:
      name: prometheus
      state: started
      enabled: yes
      daemon_reload: yes





















#- name: Setup Server
#  ansible.builtin.include_tasks: "server.yml"
#  when: prometheus == "server"
#
#- name: Setup Exporter
#  ansible.builtin.include_tasks: "exporter.yml"
#  when: prometheus == "exporter"