- name: Load MySQL Schema
  community.mysql.mysql_db:
    state: import
    name: all
    target: /app/schema/{{component}}.sql
    login_host: 10.172.0.2
    login_user: root
    login_password: "{{root_mysql_password}}"
